# Generated by Django 2.2.6 on 2020-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedata',
            name='d',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipedata',
            name='e',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipedata',
            name='site_time',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
