# Generated by Django 3.0.2 on 2020-01-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200121_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMetarialStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_metarial', models.CharField(max_length=100)),
                ('metarial_standard', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PipeLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_type_classification', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PressureTypeSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_metarial', models.CharField(max_length=100)),
                ('standard_type_classification', models.CharField(max_length=100)),
                ('pressure_type_specification', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StandardTypeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_metarial', models.CharField(max_length=100)),
                ('standard_type_classification', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PipeOuterDiameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('outer_diameter', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('standard_type_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StandardTypeClassification')),
            ],
        ),
    ]
