# Generated by Django 3.0.2 on 2020-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_basicmetarialstandard_machine_pipelength_pipeouterdiameter_plantlocation_pressuretypespecification_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicmetarialstandard',
            name='metarial_standard',
        ),
        migrations.AlterField(
            model_name='pipeouterdiameter',
            name='standard_type_classification',
            field=models.CharField(max_length=100),
        ),
    ]
