# Generated by Django 3.0.2 on 2020-01-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200125_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pipelength',
            name='standard_type_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StandardTypeClassification'),
        ),
        migrations.AlterField(
            model_name='pipeouterdiameter',
            name='standard_type_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StandardTypeClassification'),
        ),
        migrations.AlterField(
            model_name='pressuretypespecification',
            name='basic_metarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BasicMetarialStandard'),
        ),
        migrations.AlterField(
            model_name='pressuretypespecification',
            name='standard_type_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StandardTypeClassification'),
        ),
        migrations.AlterField(
            model_name='standardtypeclassification',
            name='basic_metarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BasicMetarialStandard'),
        ),
        migrations.AlterField(
            model_name='pipelength',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Unit'),
        ),
        migrations.AlterField(
            model_name='pipeouterdiameter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Unit'),
        ),
    ]
