# Generated by Django 3.0.2 on 2020-03-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200210_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='plant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlantLocation'),
        ),
    ]
