# Generated by Django 3.0.2 on 2020-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200302_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeShiftDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.CharField(max_length=8, unique=True)),
                ('shift_1', models.CharField(blank=True, max_length=10, null=True)),
                ('shift_2', models.CharField(blank=True, max_length=10, null=True)),
                ('shift_3', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
