# Generated by Django 3.0.2 on 2020-03-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pipeshiftduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date_time', models.DateTimeField()),
                ('machine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Machine')),
            ],
        ),
    ]
