# Generated by Django 3.0.4 on 2020-04-04 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20200401_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarialissueshift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeshiftduration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pipeshiftduration',
            name='shift_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='metarialissueshift',
            unique_together={('user', 'shift_date')},
        ),
        migrations.AlterUniqueTogether(
            name='pipeshiftduration',
            unique_together={('user', 'shift_date')},
        ),
    ]
