# Generated by Django 3.0.4 on 2020-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200405_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarialissueshift',
            name='shift_date',
            field=models.DateField(),
        ),
    ]
