# Generated by Django 3.0.4 on 2020-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200406_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarialissueshift',
            name='shift_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metarialissueshift',
            name='shift_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metarialissueshift',
            name='shift_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
