# Generated by Django 3.0.4 on 2020-04-15 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200406_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeData1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mid', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('e', models.TextField()),
                ('ts', models.TextField()),
                ('count', models.TextField()),
                ('weight', models.TextField()),
                ('ps', models.TextField()),
                ('site_time', models.TextField()),
                ('shift', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PipeDataProcessed1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=100)),
                ('basic_metarial', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_type_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('pressure_type_specification', models.CharField(blank=True, max_length=100, null=True)),
                ('outer_diameter', models.FloatField(blank=True, null=True)),
                ('outer_diameter_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('length_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('count', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('maxweight', models.IntegerField(blank=True, null=True)),
                ('minweight', models.IntegerField(blank=True, null=True)),
                ('weightgain', models.IntegerField(blank=True, null=True)),
                ('weightloss', models.IntegerField(blank=True, null=True)),
                ('pass_status', models.CharField(blank=True, max_length=100, null=True)),
                ('site_time', models.DateTimeField()),
                ('shift', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('machine_id', 'timestamp')},
            },
        ),
    ]
