# Generated by Django 3.1.1 on 2020-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200904_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedata',
            name='f',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pipedata',
            name='g',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pipedata',
            name='h',
            field=models.TextField(blank=True),
        ),
    ]
